on: [push]

jobs:
  my_job:    
    name: deploy to staging
    runs-on: ubuntu-latest     
    steps:   
    - uses: actions/checkout@v3   
    - uses: actions/setup-node@v3  
      with:
        node-version: 18
    - run: |
        npm install    
        npm i @crowdin/cli
        npm i crowdin
        crowdin download
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Crowdin:sync"
        git push
